#!/bin/bash

nruns=100
proccnt=0
WORKDIR=`pwd`
for (( i=1; i<=nruns; i++))
do
  outfile="run${i}.sh"
  echo -e "#!/bin/bash\n" > $outfile
  echo -e "# This file is automatically generated by generate_runscripts.sh." >> $outfile
  echo -e "WORKDIR=${WORKDIR}\n" >> $outfile
  echo -e '$WORKDIR'"/../Brem ${i}" >> $outfile
  proccnt=$((proccnt+1))
done

echo "$proccnt macro files are generated."
